#
# This is free software, license use GPLv3.
#
# Copyright (c) 2020, Chuck <fanck0605@qq.com>
#

name: openwrt-21.02

on:
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: openwrt-21.02

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo du -xh --exclude=/{proc,sys,dev} / | grep -E '^[0-9.]*?[GTPEZY]'
          docker image prune -a -f
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt update
          sudo -E apt install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools rsync subversion swig time xsltproc zlib1g-dev
          sudo -E apt autoremove --purge
          sudo -E apt clean
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"
          df -h

      - name: Build OpenWrt
        run: |
          ./build.sh
          df -h

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          echo "##[set-output name=artifact_name;]OpenWrt_$(date +%Y%m%d)_NanoPi-neo3"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.assemble_artifact.outputs.artifact_name }}
          path: artifact
